//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class News
    {
        public News()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int ID { get; set; }
        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
    }
}
